# Generated by Django 6.0.4 on 2026-04-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('general', 'General'), ('bug', 'Bug report'), ('feature', 'Feature request'), ('ui', 'UI/UX'), ('accuracy', 'Prediction accuracy')], default='general', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
