# Generated by Django 6.0.4 on 2026-04-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_Detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('user_experience', 'User experience'), ('disease_info_quality', 'Disease information quality'), ('treatment_suggestion', 'Treatment suggestion'), ('ease_of_use', 'Easy of use'), ('design_interface', 'Design and interface'), ('supported_crop_variety', 'Supported crop variety'), ('language_support', 'Language support'), ('recommendation_improvement', 'Recommendation & improvement')], default='user_experience', max_length=40),
        ),
    ]
