# Generated by Django 6.0.4 on 2026-04-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_Detection', '0002_alter_feedback_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=512)),
                ('disease', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('all_predictions', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
